# chore: fix flaky bad_tcp test (#2125)
The error stems from `econnrefused` vs. `:noproc` which, best as I could tell, stems from the warming of clients that `Clustered` does as the processes are cleaned up async from the registry which may lead to this `:noproc`.

Hence, avoid this issue by instructing Clustered not to warm the TCP connections.

```
 1) test multicall/4 partial results with bad tcp error (Realtime.GenRpcBadTcpTest)
Error:      test/realtime/gen_rpc_bad_tcp_test.exs:108
     Assertion with == failed
     code:  assert GenRpc.multicall(Map, :fetch, [%{a: 1}, :a], tenant_id: 123) == [
              {node(), {:ok, 1}},
              {node, {:error, :rpc_error, :econnrefused}}
            ]
     left:  [
              "main4@127.0.0.1": {:ok, 1},
              "peer-571426-5497@127.0.0.1": {:error, :rpc_error,
               :noproc}
            ]
     right: [
              "main4@127.0.0.1": {:ok, 1},
              "peer-571426-5497@127.0.0.1": {:error, :rpc_error,
               :econnrefused}
            ]
     stacktrace:
       (ex_unit 1.19.5) lib/ex_unit/capture_log.ex:121: ExUnit.CaptureLog.with_log/2
       (ex_unit 1.19.5) lib/ex_unit/capture_log.ex:83: ExUnit.CaptureLog.capture_log/2
       test/realtime/gen_rpc_bad_tcp_test.exs:112: (test)
```